env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:mocha/recommended
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - mocha
  - only-warn
rules: {}
