FROM node:16

COPY ./ /live-it-up/client
WORKDIR /live-it-up/client
RUN mkdir node_modules && npm ci

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL $REACT_APP_API_BASE_URL


CMD ["npm", "run", "start"]