version: '3.8'

services:
  mongodb:
    container_name: liveitup-db
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_HOST_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - backend

  server:
    container_name: liveitup-server
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: liveitup-server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SERVER_HOST_PORT:$SERVER_DOCKER_PORT
    command: npm run start
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
      - NODE_ENV=production
    networks:
      - backend
      - frontend

  client:
    container_name: liveitup-client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
    image: liveitup-client
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $CLIENT_HOST_PORT:$CLIENT_DOCKER_PORT
    depends_on:
      - server
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend: