version: '3.8'

services:
  mongodb:
    container_name: liveitup-db-dev
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_HOST_PORT:$MONGODB_HOST_PORT
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  server:
    container_name: liveitup-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: liveitup-server-dev
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SERVER_HOST_PORT:$SERVER_HOST_PORT
    expose:
      - $SERVER_HOST_PORT
    volumes:
      - ./server/app:/live-it-up/server/app
    command: npm run dev
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
      - NODE_ENV=development

  client:
    container_name: liveitup-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
    image: liveitup-client-dev
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $CLIENT_HOST_PORT:$CLIENT_HOST_PORT
    expose:
      - $CLIENT_HOST_PORT
    volumes:
      - ./client/src:/live-it-up/client/src
      - ./client/public:/live-it-up/client/public
    depends_on:
      - server
    command: npm run start

volumes:
  db: