export const CREATE_COMMITTEE = "CREATE_COMMITTEE";
export const LOAD_COMMITTEES_SUCCESS = "LOAD_COMMITTEES_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

export const CREATE_USER = "CREATE_USER";
export const LOAD_ALL_USERS = "LOAD_ALL_USERS";

