name: Build Docker images for development

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker dev image
      run: docker-compose up -f docker-compose-dev.yml -d
