name: Lint Codebase

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: self-hosted
    environment: Development

    steps:
    - uses: actions/checkout@v2

    - name: Lint the backend
      run: |
        eslint -c server/.eslintrc.yml server/server.js server/app/**/*.js --max-warnings=0

    - name: Lint the frontend
      if: always()
      run: |
        eslint -c client/.eslintrc.yml client/serc/**/*.js --max-warnings=0