
name: Lint Codebase

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  lint:

    runs-on: self-hosted
    environment: Development

    steps:
    - uses: actions/checkout@v2
    - name: Lint frontend and backend
      run: |
        npm install -g eslint
        eslint ./src/**/*.js --max-warnings=0
        eslint ./server.js ./app/**/*.js --max-warnings=0